version: '3.8'

services:

  db_server:
    container_name: db_server
    # restart: always
    build:
      context: .
      dockerfile: ./dockers/db/Dockerfile
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - ENV=test
      - POSTGRES_DB=test_db

  api_server:
    container_name: api_server
    # restart: unless-stopped
    build:
      context: .
      dockerfile: ./dockers/api/Dockerfile
    ports:
      - 4000:4000
    volumes:
      # sync code by mapping
      - /usr/src/app/node_modules
      - /usr/src/app/wait-for-it
      - ./src:/usr/src/app/src
    depends_on:
      - db_server
    env_file: ./.env
    environment:
      - POSTGRES_HOST=db_server
      - POSTGRES_DB=test_db
      - ENV=test
    command: npm run start

volumes:
  data:
