version: '3.4'

services:
  restapistorepostgreexpress:
    image: restapistorepostgreexpress
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5432:5432
      - 5432:5432
