version: '3.4'

services:
  restapistorepostgreexpress:
    image: restapistorepostgreexpress
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5432:5432
      - 5432:5432
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
